- role: PatientRegistration
  app: patient
  module: models
  class_name: PatientDetail

- role: Clinic
  app: clinic
  module: models
  class_name: Clinic

- role: Search
  app: search
  module: models
  class_name: Search


######################################################
- role: RegistryApp
  app: registry.icd10
  module: models
  class_name: Chapter

- role: RegistryApp
  app: registry.icd10pcs
  module: models
  class_name: Section

- role: RegistryApp
  app: registry.drug_db
  module: models
  class_name: FDADrugs

- role: RegistryApp
  app: registry.drug_db.drugbankca
  module: models
  class_name: DrugBankCaDrugs

- role: RegistryApp
  app: registry.vaccine_registry
  module: models
  class_name: VaccineDetail

#######################################################

